// Pays proposés pour les profils et projets entrepreneurs : Afrique + Caraïbes
// (y compris les DOM-TOM français des Caraïbes), conformément au positionnement de Pitchorium.

export const AFRICA_COUNTRIES = [
  'Afrique du Sud',
  'Algérie',
  'Angola',
  'Bénin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cameroun',
  'Comores',
  'Congo-Brazzaville',
  'Congo (RDC)',
  "Côte d'Ivoire",
  'Djibouti',
  'Égypte',
  'Érythrée',
  'Eswatini',
  'Éthiopie',
  'Gabon',
  'Gambie',
  'Ghana',
  'Guinée',
  'Guinée équatoriale',
  'Guinée-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libye',
  'Madagascar',
  'Malawi',
  'Mali',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Mozambique',
  'Namibie',
  'Niger',
  'Nigeria',
  'Ouganda',
  'République centrafricaine',
  'Rwanda',
  'Sao Tomé-et-Principe',
  'Sénégal',
  'Seychelles',
  'Sierra Leone',
  'Somalie',
  'Soudan',
  'Soudan du Sud',
  'Tanzanie',
  'Tchad',
  'Togo',
  'Tunisie',
  'Zambie',
  'Zimbabwe',
] as const;

export const CARIBBEAN_COUNTRIES = [
  // Caraïbes indépendantes
  'Antigua-et-Barbuda',
  'Bahamas',
  'Barbade',
  'Cuba',
  'Dominique',
  'République dominicaine',
  'Grenade',
  'Haïti',
  'Jamaïque',
  'Saint-Christophe-et-Niévès',
  'Sainte-Lucie',
  'Saint-Vincent-et-les-Grenadines',
  'Trinité-et-Tobago',
  // DOM-TOM français des Caraïbes
  'Guadeloupe',
  'Martinique',
  'Guyane',
  'Saint-Martin',
  'Saint-Barthélemy',
] as const;

export const AFRICA_ACP_COUNTRIES = [...AFRICA_COUNTRIES, ...CARIBBEAN_COUNTRIES].sort((a, b) =>
  a.localeCompare(b, 'fr')
);
